### ISSUE TITLE
Exclude Firefox "Bookmarks Toolbar"

### ISSUE THREAD

**Issue by wes-novack** [heftig/sort-bookmarks#17]
Hello! I'd like to the ability to exclude the Firefox "Bookmarks Toolbar" top level bookmarks from the automatic sorting. 

Thanks for your work on this wonderful extension!

**Comment by heftig** [comment]
You should be able to do this already. Right-click on a bookmark or separator in the "Bookmarks Toolbar" folder and choose "Sort this folder" (custom menu items don't appear in the menu for the special folder itself, so this is a workaround).

Then choose "folders inline", "sort by nothing", turn off "always keep sorted" and confirm.

**Comment by wes-novack** [comment]
Ah, yes, that works, thank you!

**Comment by nisc** [comment]
Phew, once I saw that there was a closed issue, I immediately realized what the solution is. But not 100% intuitive.
