### ISSUE TITLE
Bookmarks Toolbar

### ISSUE THREAD

**Issue by paulderdash** [heftig/sort-bookmarks#2]
Does it sort this as well? I would want to exclude this.

**Comment by heftig** [comment]
Yes, it's sorted as well. Ignoring folders is on the wishlist.

**Comment by paulderdash** [comment]
Thanks.

Looking forward to that feature.

Paul

On 19 August 2017 at 18:16, Jan Alexander Steffens <notifications@github.com

**Comment by heftig** [comment]
You can now set "Folders inline, sort by Nothing" for the toolbar, which keeps the existing order. Open the context menu for one of your toolbar bookmarks and click the new item.
