### ISSUE TITLE
Issue with Separators

### ISSUE THREAD

**Issue by scooby1** [heftig/sort-bookmarks#4]
I have withdrawn ALL comments as I have now uninstalled and reinstalled "Sort Bookmarks" and the new issues I was noticing have been rectified.  Not sure what messed things up (maybe another add-on I have installed or tested  in the last few days or, maybe I did something stupid when installing Firefox Nightly to check it out.

Please feel free to delete this #4

Sorry for inconvenience

**Comment by heftig** [comment]
Firefox Nightly recently started handling bookmarks off-main-thread, see https://www.thebanners.uk/standard8/2017/09/05/bookmarks-changes-in-firefox-nightly-testing-wanted/, so this could very well be a new bug in Nightly.

**Comment by heftig** [comment]
Original issue text for posterity:
> Hi Heftig,
> 
> In the Firefox Add-ons "Sort Bookmarks" I was the first person to comment and request sorting within separators. Which you did almost immediately upon request :).
> 
> I have been noticing for a few days, that the separators in SOME dropdowns SOMETIMES are sorted to the top of the drop down, but until tonight, I was unable to identify the trigger, which I have now identified.
> 
> What's OK
> 
> Everything is sorted OK if I click on the Sort bookmarks Button and sort, as all folders & drop downs sort and all separators within, hold their positions and sorting occurs correctly within each group.
> 
> Everything is OK if moving item(s) from one separator to another in the SAME drop down (as you have said, a limitation is that sorting does not occur automatically when moving items in SAME drop down and clicking on the SOrt Bookmarks Button is needed.
> 
> Moving an item from one drop down (or folder) TO ANOTHER does indeed automatically and correctly sort the drop down the item has been moved to
> EXCEPT
> IF the drop down that the item being moved to CONTAINS SEPARATORS. If it does, then all the separators in that drop down are automatically sorted to the top and all the bookmark item in that drop down are sorted as a single group below them. This of course requires users to reset the separator positions and groups manually again.
> 
> It is interesting that the Sort Bookmarks button does NOT affect the positions of separators and groups in drop downs, but the automatic sort does For me, this issue is 100% consistent having tested it several times on Firefox Release and the current Nightly
> 
> Hope this information helps you Heftig.
> Kind regards :)

**Comment by scooby1** [comment]
Thanks for reply (and so fast) and for the link

I agree. I was unaware of the details of Nightly changes but with my situation I feel sure it is a change in Nightly which has just moved to FF 58.  I have chosen to go back to FF Release which is currently FF55.  As Nightly has just upgraded 57 to 58, I am sure Release is about to move on to FF56 and just checking whilst I type this email [Open-mouthed smile]  I see Mozilla is already at Candidate 56.0b9 (strange so many candidates).

To be fair I was not aware of issues with 57 Nightly (or if they existed they were much less obvious. Tto be fair I only started using Nightly a few days ago (3 days with 57 and today with 58 Nightly).

I do have many add-ons 28, now mostly WebExtensions (24) which are FF57+ compatible, BUT as we know only too well, Mozilla nowadays are often changing code and methods (and breaking add-ons that were working perfectly.

It must be very hard creating WebExtensions when Nightly still is changing things that may affect newly written and working WebExtension add-ons. No wonder some authors have been reluctant to create FF57 compatible Extensions or are waiting until FF57 Release.

You and all the developers of Add-ons have my greatest sympathy (and appreciation I hasten to add) for your continuing efforts to make things better for Firefox Users (whilst Mozilla is still moving some goal posts.

Kind regards
Dave

-----------------------------------------------
