### ISSUE TITLE
Latest version does not work correctly if you move the icon into overflow menu

### ISSUE THREAD

**Issue by ghost** [heftig/sort-bookmarks#5]
Putting the icon in the overflow menu in the latest version will cause the sort button to disappear

**Comment by prof-tech** [comment]
I don't believe this is a bug. When the icon is dragged from the toolbar into the menu it is supposed to disappear from the toolbar.

**Comment by ghost** [comment]
This pic shows what I mean, the sort button is gone in the latest version.

![image](https://user-images.githubusercontent.com/16840836/30989123-993b64b0-a46a-11e7-9036-77f77e60b50a.png)

**Comment by heftig** [comment]
Yeah, I believe this is Firefox's bug not sizing the panel correctly; the window as a whole is sized right but the box containing the page is made too small.

As a workaround you can either keep the button outside the overflow menu or focus one of the form controls and hit Enter.

**Comment by ghost** [comment]
thank you for the info

**Comment by heftig** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1404871

**Comment by ghost** [comment]
Seems like this has been fixed, thanks
