### ISSUE TITLE
Exclude folders

### ISSUE THREAD

**Issue by prof-tech** [heftig/sort-bookmarks#6]
Would like to be able to specify folders to exclude from sorting.

**Comment by evmcl** [comment]
In particular, would love to not sort the Bookmarks Toolbar. (Although still sort bookmarks in the folders underneath.)

**Comment by heftig** [comment]
You can now set "Folders inline, sort by Nothing" for the toolbar, which keeps the existing order. Open the context menu for one of your toolbar bookmarks and click the new item.
