### ISSUE TITLE
Firefox crashes upon closing window

### ISSUE THREAD

**Issue by BugHe** [heftig/sort-bookmarks#7]
Hi, this add-on (Sort Bookmarks 0.4) apparently causes Firefox (57.9×64) either to silently crash upon close or not to open correctly. At new Firefox start, there is an error message displayed that sorry, the windows could not be recovered (though pushing the corresponding button works !). Note that my Firefox is configured always to open with an empty window but this does only work when I disable Sort Bookmarks ! Reproducable >5×

**Comment by heftig** [comment]
Is this still an issue?
