### ISSUE TITLE
Build 0.4 no longer works for me on FF 56.0.2 Win64

### ISSUE THREAD

**Issue by FredThompsonII** [heftig/sort-bookmarks#8]
When I click on the icon, there is no change to the list of bookmarks. This happens with or without uBlock Origin enabled. I don't see anything in prefs.js or user.js which should cause a conflict but I only searched for the string "book." Are there any known config settings which would prevent sort-bookmarks from running properly?

FWIW, This is a great extension. It has very low overhead and isn't full of fluff.

**Comment by heftig** [comment]
Clicking the icon should just open the configuration popup. Does this no longer happen?

**Comment by FredThompsonII** [comment]
Yes, the menu shows but sorting does not happen.

**Comment by heftig** [comment]
Did this stop working with an update to 0.4?
Firefox 56 is quite old and not an ESR release. Do you mean 58.0.2?

**Comment by heftig** [comment]
Closing an old issue without response.
