### ISSUE TITLE
Default for all bookmarks

### ISSUE THREAD

**Issue by Sirove** [heftig/sort-bookmarks#9]
Thank you for work! An option to configure a default "folder" for all bookmarks would be a nice enhancement. The current default on desktop systems is "Unsorted" and with Android it's "Mobile" which get's pretty messy with over a thousand bookmarks.

**Comment by heftig** [comment]
I think moving bookmarks between folders will remain out-of-scope for this extension. However, I believe it should pair well with other minimalist extensions that move bookmarks between folders (using whatever criteria).
